apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth
  labels:
    app: api-auth
spec:
  replicas: 0
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
        - name: api-auth
          image: docker.io/solarianetwork/api-auth:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
