apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-database
  labels:
    app: mcp-database
spec:
  replicas: 0
  selector:
    matchLabels:
      app: mcp-database
  template:
    metadata:
      labels:
        app: mcp-database
    spec:
      containers:
        - name: mcp-database
          image: docker.io/solarianetwork/mcp-database:latest
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: mcp-database-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 20
