apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-http01
spec:
  ingressClassName: kong
  tls:
    - hosts:
        - web.solarianetwork.site
      secretName: web-app-tls
  rules:
    - host: web.solarianetwork.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app
                port:
                  number: 80
