apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-validation
spec:
  ingressClassName: kong
  rules:
    - host: ai-validation.34.42.214.54.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-validation
                port:
                  number: 8000
